/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.domain;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EventMessageDetail extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 472007443198451042L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EventMessageDetail\",\"namespace\":\"com.example.domain\",\"fields\":[{\"name\":\"msgId\",\"type\":\"string\"},{\"name\":\"contact\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EventMessageDetail> ENCODER =
      new BinaryMessageEncoder<EventMessageDetail>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EventMessageDetail> DECODER =
      new BinaryMessageDecoder<EventMessageDetail>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EventMessageDetail> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EventMessageDetail> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EventMessageDetail> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EventMessageDetail>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EventMessageDetail to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EventMessageDetail from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EventMessageDetail instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EventMessageDetail fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence msgId;
   private java.lang.CharSequence contact;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EventMessageDetail() {}

  /**
   * All-args constructor.
   * @param msgId The new value for msgId
   * @param contact The new value for contact
   */
  public EventMessageDetail(java.lang.CharSequence msgId, java.lang.CharSequence contact) {
    this.msgId = msgId;
    this.contact = contact;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return msgId;
    case 1: return contact;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: msgId = (java.lang.CharSequence)value$; break;
    case 1: contact = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'msgId' field.
   * @return The value of the 'msgId' field.
   */
  public java.lang.CharSequence getMsgId() {
    return msgId;
  }


  /**
   * Sets the value of the 'msgId' field.
   * @param value the value to set.
   */
  public void setMsgId(java.lang.CharSequence value) {
    this.msgId = value;
  }

  /**
   * Gets the value of the 'contact' field.
   * @return The value of the 'contact' field.
   */
  public java.lang.CharSequence getContact() {
    return contact;
  }


  /**
   * Sets the value of the 'contact' field.
   * @param value the value to set.
   */
  public void setContact(java.lang.CharSequence value) {
    this.contact = value;
  }

  /**
   * Creates a new EventMessageDetail RecordBuilder.
   * @return A new EventMessageDetail RecordBuilder
   */
  public static com.example.domain.EventMessageDetail.Builder newBuilder() {
    return new com.example.domain.EventMessageDetail.Builder();
  }

  /**
   * Creates a new EventMessageDetail RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EventMessageDetail RecordBuilder
   */
  public static com.example.domain.EventMessageDetail.Builder newBuilder(com.example.domain.EventMessageDetail.Builder other) {
    if (other == null) {
      return new com.example.domain.EventMessageDetail.Builder();
    } else {
      return new com.example.domain.EventMessageDetail.Builder(other);
    }
  }

  /**
   * Creates a new EventMessageDetail RecordBuilder by copying an existing EventMessageDetail instance.
   * @param other The existing instance to copy.
   * @return A new EventMessageDetail RecordBuilder
   */
  public static com.example.domain.EventMessageDetail.Builder newBuilder(com.example.domain.EventMessageDetail other) {
    if (other == null) {
      return new com.example.domain.EventMessageDetail.Builder();
    } else {
      return new com.example.domain.EventMessageDetail.Builder(other);
    }
  }

  /**
   * RecordBuilder for EventMessageDetail instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EventMessageDetail>
    implements org.apache.avro.data.RecordBuilder<EventMessageDetail> {

    private java.lang.CharSequence msgId;
    private java.lang.CharSequence contact;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.domain.EventMessageDetail.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.msgId)) {
        this.msgId = data().deepCopy(fields()[0].schema(), other.msgId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.contact)) {
        this.contact = data().deepCopy(fields()[1].schema(), other.contact);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing EventMessageDetail instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.domain.EventMessageDetail other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.msgId)) {
        this.msgId = data().deepCopy(fields()[0].schema(), other.msgId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.contact)) {
        this.contact = data().deepCopy(fields()[1].schema(), other.contact);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'msgId' field.
      * @return The value.
      */
    public java.lang.CharSequence getMsgId() {
      return msgId;
    }


    /**
      * Sets the value of the 'msgId' field.
      * @param value The value of 'msgId'.
      * @return This builder.
      */
    public com.example.domain.EventMessageDetail.Builder setMsgId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.msgId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'msgId' field has been set.
      * @return True if the 'msgId' field has been set, false otherwise.
      */
    public boolean hasMsgId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'msgId' field.
      * @return This builder.
      */
    public com.example.domain.EventMessageDetail.Builder clearMsgId() {
      msgId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'contact' field.
      * @return The value.
      */
    public java.lang.CharSequence getContact() {
      return contact;
    }


    /**
      * Sets the value of the 'contact' field.
      * @param value The value of 'contact'.
      * @return This builder.
      */
    public com.example.domain.EventMessageDetail.Builder setContact(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.contact = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'contact' field has been set.
      * @return True if the 'contact' field has been set, false otherwise.
      */
    public boolean hasContact() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'contact' field.
      * @return This builder.
      */
    public com.example.domain.EventMessageDetail.Builder clearContact() {
      contact = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EventMessageDetail build() {
      try {
        EventMessageDetail record = new EventMessageDetail();
        record.msgId = fieldSetFlags()[0] ? this.msgId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.contact = fieldSetFlags()[1] ? this.contact : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EventMessageDetail>
    WRITER$ = (org.apache.avro.io.DatumWriter<EventMessageDetail>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EventMessageDetail>
    READER$ = (org.apache.avro.io.DatumReader<EventMessageDetail>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.msgId);

    out.writeString(this.contact);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.msgId = in.readString(this.msgId instanceof Utf8 ? (Utf8)this.msgId : null);

      this.contact = in.readString(this.contact instanceof Utf8 ? (Utf8)this.contact : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.msgId = in.readString(this.msgId instanceof Utf8 ? (Utf8)this.msgId : null);
          break;

        case 1:
          this.contact = in.readString(this.contact instanceof Utf8 ? (Utf8)this.contact : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










